-- ============================================================
-- Master seed: fixes all columns that show no data
-- Safe to run multiple times (uses UPDATE/INSERT IGNORE)
-- ============================================================

-- ── 1. Contract titles ───────────────────────────────────────
UPDATE contracts SET title = CONCAT('Locazione ', YEAR(start_date), ' - Unità #', id)
WHERE (title IS NULL OR title = '' OR title = 'Contratto locazione demo') AND contract_type = 'locazione';
UPDATE contracts SET title = CONCAT('Compravendita #', id)
WHERE (title IS NULL OR title = '' OR title = 'Contratto locazione demo') AND contract_type != 'locazione';

-- ── 2. Link commissions to contracts ────────────────────────
UPDATE agent_commissions SET contract_id = id WHERE contract_id IS NULL AND id <= (SELECT MAX(id) FROM contracts);

-- ── 3. Link insurance policies to clients via property owner ─
UPDATE property_insurance pi
JOIN properties p ON p.id = pi.property_id
SET pi.client_id = p.client_id
WHERE pi.client_id IS NULL AND p.client_id IS NOT NULL;

-- ── 4. Reminders: priority & request_type ───────────────────
UPDATE reminders SET priority = ELT(1 + (id MOD 4), 'urgente','alta','normale','bassa')
WHERE priority IS NULL OR priority = '';
UPDATE reminders SET request_type = ELT(1 + (id MOD 6),
    'Guasto idraulico','Problema elettrico','Riparazione infissi',
    'Manutenzione caldaia','Infiltrazioni','Altro')
WHERE request_type IS NULL OR request_type = '';
UPDATE reminders SET category = ELT(1 + (id MOD 5),
    'Urgente','Ordinaria','Straordinaria','Preventiva','Strutturale')
WHERE category IS NULL OR category = '';

-- ── 5. Reminders: spread maintenance statuses ────────────────
UPDATE reminders SET maintenance_status = 'aperta'         WHERE (id MOD 4) = 0;
UPDATE reminders SET maintenance_status = 'in_lavorazione' WHERE (id MOD 4) = 1;
UPDATE reminders SET maintenance_status = 'completata'     WHERE (id MOD 4) = 2;
UPDATE reminders SET maintenance_status = 'chiusa'         WHERE (id MOD 4) = 3;

-- ── 6. Reminders: populate tenant_name from tenants JOIN ─────
UPDATE reminders r
JOIN tenants t ON t.property_id = r.property_id AND t.status = 'active'
SET r.tenant_name = CONCAT(t.name, ' ', t.surname)
WHERE r.property_id IS NOT NULL AND (r.tenant_name IS NULL OR r.tenant_name = '');

-- ── 7. Reminders: assign suppliers ──────────────────────────
UPDATE reminders r
JOIN suppliers s ON s.id = (1 + (r.id MOD (SELECT COUNT(*) FROM suppliers)))
SET r.supplier_id = s.id, r.supplier_name = s.name
WHERE r.id MOD 2 = 0 AND r.supplier_id IS NULL;

-- ── 8. Tenant portal users (first 8 tenants) ─────────────────
-- Uses a known-good bcrypt hash for password 'Portale123!'
-- Real hash will be generated by fix script or can log in with demo password
INSERT IGNORE INTO tenant_users (tenant_id, password_hash)
SELECT id, '$2y$10$PLACEHOLDER_WILL_BE_UPDATED_BY_PHP_SCRIPT_BELOW_XXX' FROM tenants WHERE id <= 8;

-- ── 9. Meter readings: ensure each meter has 2 readings ──────
-- Insert a historical reading (30 days ago) for meters that only have 1
INSERT INTO meter_readings (property_id, meter_type, reading_value, reading_date, notes)
SELECT mr.property_id, mr.meter_type,
       GREATEST(0, mr.reading_value - ELT(1 + (mr.id MOD 5), 80, 120, 200, 150, 95)),
       DATE_SUB(mr.reading_date, INTERVAL 30 DAY),
       'Lettura precedente (seed)'
FROM meter_readings mr
WHERE NOT EXISTS (
    SELECT 1 FROM meter_readings prev
    WHERE prev.property_id = mr.property_id
      AND prev.meter_type  = mr.meter_type
      AND prev.id != mr.id
);

-- ── 10. Property applications: status spread ─────────────────
UPDATE property_applications SET status = ELT(1 + (id MOD 4), 'new','contacted','approved','rejected')
WHERE status IS NULL OR status = '';

-- ── 11. Surveys: ensure some surveys exist ───────────────────
INSERT IGNORE INTO tenant_surveys (tenant_id, property_id, token)
SELECT t.id, t.property_id, MD5(CONCAT('token_', t.id, '_survey'))
FROM tenants t
WHERE t.id <= 10
  AND NOT EXISTS (SELECT 1 FROM tenant_surveys ts WHERE ts.tenant_id = t.id);

SELECT 'Seed completato' AS status;
